steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$BRANCH_NAME-$SHORT_SHA', '.']
images:
- '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$BRANCH_NAME-$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY