steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build', '-t', 'europe-central2-docker.pkg.dev/$PROJECT_ID/digital-dice/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA', '.']
images:
- 'europe-central2-docker.pkg.dev/$PROJECT_ID/digital-dice/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA'
- name: "gcr.io/cloud-builders/gke-deploy"
  id: Deploy
  args: 
  - run
  - --filename=k8s/deployment.yml 
  - --image=europe-central2-docker.pkg.dev/$PROJECT_ID/digital-dice/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA
  - --cluster=dd-game-non-prod
  - --location=europe-central2

options:
  logging: CLOUD_LOGGING_ONLY