steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build', '-t', 'europe-central2-docker.pkg.dev/striking-arbor-382117/game-config-service:$BRANCH_NAME-$SHORT_SHA', '.']
images:
- 'europe-central2-docker.pkg.dev/striking-arbor-382117/game-config-service:$BRANCH_NAME-$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY