steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build', '-t', 'europe-central2-docker.pkg.dev/$PROJECT_ID/digital-dice/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args: ['push', 'europe-central2-docker.pkg.dev/$PROJECT_ID/digital-dice/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA']
- name: 'ubuntu'
  id: Inject Envs
  args: ['bash','-c', 'sed -i "s/IMAGE_TAG/${BRANCH_NAME}-${SHORT_SHA}/g" k8s/deployment.yml && cp k8s/deployment.yml /workspace/deployment.yml']
- name: "gcr.io/cloud-builders/gke-deploy"
  id: Deploy
  args: 
  - run
  - --filename=/workspace/deployment.yml 
  - --image=europe-central2-docker.pkg.dev/$PROJECT_ID/digital-dice/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA
  - --cluster=dd-game-non-prod
  - --location=europe-central2

options:
  logging: CLOUD_LOGGING_ONLY