apiVersion: v1
kind: Service
metadata:
  name: game-config-service
  labels:
    app: game-config-service
spec:
  selector:
    app: game-config-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: game-config-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1   
spec:
  rules:
    - host: digitaldice.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: game-config-service
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-config-service
  labels:
    app: game-config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-config-service
  template:
    metadata:
      labels:
        app: game-config-service
    spec:
      containers:
      - name: game-config-service
        image: game-config-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "dev"
        - name: DB_HOST
          value: "kubernetes.docker.internal"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_NAME
          value: "gamedb"
        - name: REDIS_HOST
          value: "kubernetes.docker.internal"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 512Mi