apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: game-config-depl
  labels:
    app: game-config-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-config-depl
  template:
    metadata:
      labels:
        app: game-config-depl
    spec:
      imagePullSecrets:
      - name: registry-digital-dice
      containers:
      - name: game-config-depl
        image: registry.digitalocean.com/digital-dice/game-config:image_tag
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "dev"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-password
              key: host
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-password
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-password
              key: database
        - name: REDIS_HOST
          value: "kubernetes.docker.internal"
        - name: REDIS_PORT
          value: "6379"
        livenessProbe:
          httpGet:
           path: /health
           port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
           path: /health
           port: 8000
           scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 512Mi