name: Build and push Docker image
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'k8s/**'
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
env:
  REGISTRY: "registry.digitalocean.com/digital-dice"
  IMAGE_NAME: "game-config"
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
        
      - name: Build container image
        run: docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)

      - name: kustomize download
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

      - name: kustomize apply new image tag
        run: cd k8s && kustomize edit set image $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)

      - name: remove kusstomize file
        run: rm -rf kustomize

      - name: push to git
        run: |
          git config --global user.email "dgokadze@gmail.com"
          git config --global user.name "GitHub Actions"
          git add k8s/kustomization.yaml
          git commit -m "Update kustomize file"
          git push